### ISSUE TITLE
Driver does not work after kernel update

### ISSUE THREAD

**Issue by paoloperrone** [jlam55555/veikk-linux-driver#31]
It seems that every time I update the kernel, the driver does not work anymore, and needs to be reinstalled. 
Anybody can reproduce?

**Comment by jlam55555** [comment]
You're correct, this driver is a LKM that must be recompiled with a kernel update-- it's not compiled into the kernel.

If you want to have it (or any other LKM) automatically update on a kernel update, you can use something like DKMS. Unfortunately, I haven't implemented this (yet), but if you're on Arch you can use [this AUR package](https://aur.archlinux.org/packages/input-veikk-dkms/) built by @artixnous. (Even if you are not on archlinux, you can view the PKGBUILD and dkms.conf for that package to get an idea of how to do that.)
