### ISSUE TITLE
How to Make Veikk A 15v Pro Work

### ISSUE THREAD

**Issue by maximusdaniel** [jlam55555/veikk-linux-driver#45]
I'm a newbie to linux, and don't know anything more than the basic sudo terminal codes.
I've the veikk a 15 pro tab which works fine on windows. I wan't to make it work with linux.
however when i tried ur package the terminal throws some error which i couldn't even decipher with my little linux knowledge.

sudo make all install clean
make -C /lib/modules/5.4.0-42-generic/build M=/home/maxdan/Downloads/veikk-linux-driver-3-alpha-ff0a modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-42-generic'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-42-generic'
make -C /lib/modules/5.4.0-42-generic/build M=/home/maxdan/Downloads/veikk-linux-driver-3-alpha-ff0a modules_install
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-42-generic'
  INSTALL /home/maxdan/Downloads/veikk-linux-driver-3-alpha-ff0a/veikk.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  5.4.0-42-generic
Warning: modules_install: missing 'System.map' file. Skipping depmod.
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-42-generic'
modprobe veikk
modprobe: ERROR: could not insert 'veikk': Operation not permitted
Makefile:12: recipe for target 'install' failed
make: *** [install] Error 1

Please help me finding the correct way to install the driver. Also I saw that you re using only the 640 device, but if u teach me to compile these files i'll lend a hand to you for making a driver for a 15 pro by testing on my device.

**Comment by jlam55555** [comment]
This specific error appears to be with Secure Boot enabled and without manually signing the driver. Reopen if you're still having this issue with Secure Boot disabled.
