### ISSUE TITLE
Configuration does not persist if I restart Computer and also unplug device

### ISSUE THREAD

**Issue by rohan-paul** [jlam55555/veikk-linux-driver#48]
For the GUI I am using - [veikk-linux-driver-gui](https://github.com/jlam55555/veikk-linux-driver-gui)

In Ubuntu 20.04 - The configuration persists if I just unplug the device and replug. 

Configuration also persists, if I restart machine but don't unplug the device. 

#### But does NOT persist if I restart Computer and also unplug device

**Comment by jlam55555** [comment]
Closing issue here. Will respond in [issue](https://github.com/jlam55555/veikk-linux-driver-gui/issues/8) in other repo.
