### ISSUE TITLE
Veikk tablet does not affect the cursor, what's wrong?

### ISSUE THREAD

**Issue by fallsixgirl** [jlam55555/veikk-linux-driver#50]
I'm definitely using manjaro before, but now i'm changing into ubuntu due to i can't _make_ on my konsole. I thought it would be plug and play, but it doesn't affect my cursor at all. I have no idea cause i'm still learning.

**Comment by jlam55555** [comment]
Closing now. Let me know if you still have this issue (and have read the instructions on the README, including prerequisites).
