### ISSUE TITLE
After succesfully installing the driver. Pressure can be read but not in Krita

### ISSUE THREAD

**Issue by skyofglass** [jlam55555/veikk-linux-driver#55]
I'm able to get through the full instalation and can confirm the pen pressure works in Gimp with my A15. However, when I try to draw in krita there is no pen pressure, and when I check the settings it doesnt alter the pen pressure. Is there any way around this issue?

**Comment by jobins1492** [comment]
Try Different pen like the pencil tool in Krita as only some brushes support pressure sensitivity(Even in Windows) in Krita.

**Comment by jlam55555** [comment]
Closing because this doesn't seem to be an issue with the driver.
