### ISSUE TITLE
manjaro support?

### ISSUE THREAD

**Issue by komiyamao** [jlam55555/veikk-linux-driver#57]
does this support manjaro? im thinking of switching to manjaro, but I'm an osu player and I have a veikk tablet. does this support manjaro?

**Comment by hayriyigit** [comment]
Check: https://www.youtube.com/watch?v=IzazndBhrMg

Install these on Arch/Manjaro:

```
sudo pacman -S git
sudo pacman -S linux-headers
sudo pacman -S base-devel
```
Installing the drivers:

```
git clone https://github.com/jlam55555/veikk-linux-driver.git
cd veikk-linux-driver
make
sudo make all install clean
```

**Comment by jlam55555** [comment]
Hopefully @hayriyigit's comment helps. This should work for any major Linux distro. Closing.
