### ISSUE TITLE
Unrecognised stylus

### ISSUE THREAD

**Issue by insciencewetrust** [jlam55555/veikk-linux-driver#61]
My Linux devices recognise my Veikk VK 640 graphics tablet as a keyboard and its stylus as a mouse. It is not supposed to be recognised as a mouse anyway, but I can't even move the cursor with the stylus. The tablet itself probably works, as the shortcut keys are okay. I properly installed the driver, but the problem remains.

I also want to note that I experience it regardless of the distribution I am using. I'm using Arch Linux on my desktop and two of my laptops, and the stylus was dysfunctional on all of them. However, I also tested it on Mint, and it was again the same issue. Just to make sure that the hardware of the tablet was all right, I borrowed a Windows PC and tested the tablet there; it is perfectly fine.

**Comment by asl97** [comment]
From what I can tell, the VK 640 is a new model, released after the latest commit as of writing this, chances are, it's not supported and the driver isn't actually loaded for it.

https://github.com/jlam55555/veikk-linux-driver/blob/bb938f011669993473ea8938f1585a3c15605fbb/veikk_vdev.c#L222-L230

It should still fall back to the default linux driver even if linux is still not officially support by veikk.
