### ISSUE TITLE
VK640 tilt support

### ISSUE THREAD

**Issue by RushingAlien** [jlam55555/veikk-linux-driver#64]
Hello! The Veikk VK640 tablet has a tilt funtionality. A PR #63  has been made to enable this functionality by @Bloody-Badboy. I am only trying to be a reminder for this PR since there has been virtually no comment made. Thank you for your attention.

**Comment by jlam55555** [comment]
Thanks for bringing it up and sorry for my absence. I will close this issue and continue the discussion on the PR page.
